<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nationalities = [
            'AF' => ['nationality' => 'Afghan', 'nationality_ar' => 'أفغاني'],
            'AL' => ['nationality' => 'Albanian', 'nationality_ar' => 'ألباني'],
            'DZ' => ['nationality' => 'Algerian', 'nationality_ar' => 'جزائري'],
            'AD' => ['nationality' => 'Andorran', 'nationality_ar' => 'أندوري'],
            'AO' => ['nationality' => 'Angolan', 'nationality_ar' => 'أنغولي'],
            'AG' => ['nationality' => 'Antiguan', 'nationality_ar' => 'أنتيغوي'],
            'AR' => ['nationality' => 'Argentine', 'nationality_ar' => 'أرجنتيني'],
            'AM' => ['nationality' => 'Armenian', 'nationality_ar' => 'أرميني'],
            'AU' => ['nationality' => 'Australian', 'nationality_ar' => 'أسترالي'],
            'AT' => ['nationality' => 'Austrian', 'nationality_ar' => 'نمساوي'],
            'AZ' => ['nationality' => 'Azerbaijani', 'nationality_ar' => 'أذربيجاني'],
            'BS' => ['nationality' => 'Bahamian', 'nationality_ar' => 'باهامي'],
            'BH' => ['nationality' => 'Bahraini', 'nationality_ar' => 'بحريني'],
            'BD' => ['nationality' => 'Bangladeshi', 'nationality_ar' => 'بنغلاديشي'],
            'BB' => ['nationality' => 'Barbadian', 'nationality_ar' => 'بربادوسي'],
            'BY' => ['nationality' => 'Belarusian', 'nationality_ar' => 'بيلاروسي'],
            'BE' => ['nationality' => 'Belgian', 'nationality_ar' => 'بلجيكي'],
            'BZ' => ['nationality' => 'Belizean', 'nationality_ar' => 'بليزي'],
            'BJ' => ['nationality' => 'Beninese', 'nationality_ar' => 'بنيني'],
            'BT' => ['nationality' => 'Bhutanese', 'nationality_ar' => 'بوتاني'],
            'BO' => ['nationality' => 'Bolivian', 'nationality_ar' => 'بوليفي'],
            'BA' => ['nationality' => 'Bosnian', 'nationality_ar' => 'بوسني'],
            'BW' => ['nationality' => 'Botswanan', 'nationality_ar' => 'بوتسواني'],
            'BR' => ['nationality' => 'Brazilian', 'nationality_ar' => 'برازيلي'],
            'BN' => ['nationality' => 'Bruneian', 'nationality_ar' => 'بروناي'],
            'BG' => ['nationality' => 'Bulgarian', 'nationality_ar' => 'بلغاري'],
            'BF' => ['nationality' => 'Burkinabe', 'nationality_ar' => 'بوركيني'],
            'BI' => ['nationality' => 'Burundian', 'nationality_ar' => 'بوروندي'],
            'KH' => ['nationality' => 'Cambodian', 'nationality_ar' => 'كمبودي'],
            'CM' => ['nationality' => 'Cameroonian', 'nationality_ar' => 'كاميروني'],
            'CA' => ['nationality' => 'Canadian', 'nationality_ar' => 'كندي'],
            'CV' => ['nationality' => 'Cape Verdean', 'nationality_ar' => 'رأس أخضر'],
            'CF' => ['nationality' => 'Central African', 'nationality_ar' => 'أفريقي أوسط'],
            'TD' => ['nationality' => 'Chadian', 'nationality_ar' => 'تشادي'],
            'CL' => ['nationality' => 'Chilean', 'nationality_ar' => 'تشيلي'],
            'CN' => ['nationality' => 'Chinese', 'nationality_ar' => 'صيني'],
            'CO' => ['nationality' => 'Colombian', 'nationality_ar' => 'كولومبي'],
            'KM' => ['nationality' => 'Comoran', 'nationality_ar' => 'قمري'],
            'CG' => ['nationality' => 'Congolese', 'nationality_ar' => 'كونغولي'],
            'CR' => ['nationality' => 'Costa Rican', 'nationality_ar' => 'كوستاريكي'],
            'HR' => ['nationality' => 'Croatian', 'nationality_ar' => 'كرواتي'],
            'CU' => ['nationality' => 'Cuban', 'nationality_ar' => 'كوبي'],
            'CY' => ['nationality' => 'Cypriot', 'nationality_ar' => 'قبرصي'],
            'CZ' => ['nationality' => 'Czech', 'nationality_ar' => 'تشيكي'],
            'DK' => ['nationality' => 'Danish', 'nationality_ar' => 'دنماركي'],
            'DJ' => ['nationality' => 'Djiboutian', 'nationality_ar' => 'جيبوتي'],
            'DM' => ['nationality' => 'Dominican', 'nationality_ar' => 'دومينيكي'],
            'DO' => ['nationality' => 'Dominican', 'nationality_ar' => 'دومينيكاني'],
            'EC' => ['nationality' => 'Ecuadorian', 'nationality_ar' => 'إكوادوري'],
            'EG' => ['nationality' => 'Egyptian', 'nationality_ar' => 'مصري'],
            'SV' => ['nationality' => 'Salvadoran', 'nationality_ar' => 'سلفادوري'],
            'GQ' => ['nationality' => 'Equatorial Guinean', 'nationality_ar' => 'غيني استوائي'],
            'ER' => ['nationality' => 'Eritrean', 'nationality_ar' => 'إريتري'],
            'EE' => ['nationality' => 'Estonian', 'nationality_ar' => 'إستوني'],
            'ET' => ['nationality' => 'Ethiopian', 'nationality_ar' => 'إثيوبي'],
            'FJ' => ['nationality' => 'Fijian', 'nationality_ar' => 'فيجي'],
            'FI' => ['nationality' => 'Finnish', 'nationality_ar' => 'فنلندي'],
            'FR' => ['nationality' => 'French', 'nationality_ar' => 'فرنسي'],
            'GA' => ['nationality' => 'Gabonese', 'nationality_ar' => 'غابوني'],
            'GM' => ['nationality' => 'Gambian', 'nationality_ar' => 'غامبي'],
            'GE' => ['nationality' => 'Georgian', 'nationality_ar' => 'جورجي'],
            'DE' => ['nationality' => 'German', 'nationality_ar' => 'ألماني'],
            'GH' => ['nationality' => 'Ghanaian', 'nationality_ar' => 'غاني'],
            'GR' => ['nationality' => 'Greek', 'nationality_ar' => 'يوناني'],
            'GD' => ['nationality' => 'Grenadian', 'nationality_ar' => 'غرينادي'],
            'GT' => ['nationality' => 'Guatemalan', 'nationality_ar' => 'غواتيمالي'],
            'GN' => ['nationality' => 'Guinean', 'nationality_ar' => 'غيني'],
            'GW' => ['nationality' => 'Bissau-Guinean', 'nationality_ar' => 'غيني بيساو'],
            'GY' => ['nationality' => 'Guyanese', 'nationality_ar' => 'غياني'],
            'HT' => ['nationality' => 'Haitian', 'nationality_ar' => 'هايتي'],
            'HN' => ['nationality' => 'Honduran', 'nationality_ar' => 'هندوراسي'],
            'HU' => ['nationality' => 'Hungarian', 'nationality_ar' => 'مجري'],
            'IS' => ['nationality' => 'Icelandic', 'nationality_ar' => 'آيسلندي'],
            'IN' => ['nationality' => 'Indian', 'nationality_ar' => 'هندي'],
            'ID' => ['nationality' => 'Indonesian', 'nationality_ar' => 'إندونيسي'],
            'IR' => ['nationality' => 'Iranian', 'nationality_ar' => 'إيراني'],
            'IQ' => ['nationality' => 'Iraqi', 'nationality_ar' => 'عراقي'],
            'IE' => ['nationality' => 'Irish', 'nationality_ar' => 'إيرلندي'],
            'IL' => ['nationality' => 'Israeli', 'nationality_ar' => 'إسرائيلي'],
            'IT' => ['nationality' => 'Italian', 'nationality_ar' => 'إيطالي'],
            'CI' => ['nationality' => 'Ivorian', 'nationality_ar' => 'إيفواري'],
            'JM' => ['nationality' => 'Jamaican', 'nationality_ar' => 'جامايكي'],
            'JP' => ['nationality' => 'Japanese', 'nationality_ar' => 'ياباني'],
            'JO' => ['nationality' => 'Jordanian', 'nationality_ar' => 'أردني'],
            'KZ' => ['nationality' => 'Kazakhstani', 'nationality_ar' => 'كازاخستاني'],
            'KE' => ['nationality' => 'Kenyan', 'nationality_ar' => 'كيني'],
            'KI' => ['nationality' => 'I-Kiribati', 'nationality_ar' => 'كيريباتي'],
            'KP' => ['nationality' => 'North Korean', 'nationality_ar' => 'كوري شمالي'],
            'KR' => ['nationality' => 'South Korean', 'nationality_ar' => 'كوري جنوبي'],
            'KW' => ['nationality' => 'Kuwaiti', 'nationality_ar' => 'كويتي'],
            'KG' => ['nationality' => 'Kyrgyz', 'nationality_ar' => 'قيرغيزي'],
            'LA' => ['nationality' => 'Laotian', 'nationality_ar' => 'لاوسي'],
            'LV' => ['nationality' => 'Latvian', 'nationality_ar' => 'لاتفي'],
            'LB' => ['nationality' => 'Lebanese', 'nationality_ar' => 'لبناني'],
            'LS' => ['nationality' => 'Basotho', 'nationality_ar' => 'ليسوتي'],
            'LR' => ['nationality' => 'Liberian', 'nationality_ar' => 'ليبيري'],
            'LY' => ['nationality' => 'Libyan', 'nationality_ar' => 'ليبي'],
            'LI' => ['nationality' => 'Liechtensteiner', 'nationality_ar' => 'ليختنشتايني'],
            'LT' => ['nationality' => 'Lithuanian', 'nationality_ar' => 'ليتواني'],
            'LU' => ['nationality' => 'Luxembourger', 'nationality_ar' => 'لوكسمبورغي'],
            'MK' => ['nationality' => 'Macedonian', 'nationality_ar' => 'مقدوني'],
            'MG' => ['nationality' => 'Malagasy', 'nationality_ar' => 'مدغشقري'],
            'MW' => ['nationality' => 'Malawian', 'nationality_ar' => 'ملاوي'],
            'MY' => ['nationality' => 'Malaysian', 'nationality_ar' => 'ماليزي'],
            'MV' => ['nationality' => 'Maldivian', 'nationality_ar' => 'مالديفي'],
            'ML' => ['nationality' => 'Malian', 'nationality_ar' => 'مالي'],
            'MT' => ['nationality' => 'Maltese', 'nationality_ar' => 'مالطي'],
            'MH' => ['nationality' => 'Marshallese', 'nationality_ar' => 'مارشالي'],
            'MR' => ['nationality' => 'Mauritanian', 'nationality_ar' => 'موريتاني'],
            'MU' => ['nationality' => 'Mauritian', 'nationality_ar' => 'موريشيوسي'],
            'MX' => ['nationality' => 'Mexican', 'nationality_ar' => 'مكسيكي'],
            'FM' => ['nationality' => 'Micronesian', 'nationality_ar' => 'ميكرونيزي'],
            'MD' => ['nationality' => 'Moldovan', 'nationality_ar' => 'مولدوفي'],
            'MC' => ['nationality' => 'Monegasque', 'nationality_ar' => 'موناكي'],
            'MN' => ['nationality' => 'Mongolian', 'nationality_ar' => 'منغولي'],
            'ME' => ['nationality' => 'Montenegrin', 'nationality_ar' => 'جبل أسود'],
            'MA' => ['nationality' => 'Moroccan', 'nationality_ar' => 'مغربي'],
            'MZ' => ['nationality' => 'Mozambican', 'nationality_ar' => 'موزمبيقي'],
            'MM' => ['nationality' => 'Burmese', 'nationality_ar' => 'بورمي'],
            'NA' => ['nationality' => 'Namibian', 'nationality_ar' => 'ناميبي'],
            'NR' => ['nationality' => 'Nauruan', 'nationality_ar' => 'ناوري'],
            'NP' => ['nationality' => 'Nepalese', 'nationality_ar' => 'نيبالي'],
            'NL' => ['nationality' => 'Dutch', 'nationality_ar' => 'هولندي'],
            'NZ' => ['nationality' => 'New Zealander', 'nationality_ar' => 'نيوزيلندي'],
            'NI' => ['nationality' => 'Nicaraguan', 'nationality_ar' => 'نيكاراغوي'],
            'NE' => ['nationality' => 'Nigerien', 'nationality_ar' => 'نيجري'],
            'NG' => ['nationality' => 'Nigerian', 'nationality_ar' => 'نيجيري'],
            'NO' => ['nationality' => 'Norwegian', 'nationality_ar' => 'نرويجي'],
            'OM' => ['nationality' => 'Omani', 'nationality_ar' => 'عماني'],
            'PK' => ['nationality' => 'Pakistani', 'nationality_ar' => 'باكستاني'],
            'PW' => ['nationality' => 'Palauan', 'nationality_ar' => 'بالاوي'],
            'PS' => ['nationality' => 'Palestinian', 'nationality_ar' => 'فلسطيني'],
            'PA' => ['nationality' => 'Panamanian', 'nationality_ar' => 'بنمي'],
            'PG' => ['nationality' => 'Papua New Guinean', 'nationality_ar' => 'بابوا غينيا'],
            'PY' => ['nationality' => 'Paraguayan', 'nationality_ar' => 'باراغواي'],
            'PE' => ['nationality' => 'Peruvian', 'nationality_ar' => 'بيروفي'],
            'PH' => ['nationality' => 'Filipino', 'nationality_ar' => 'فلبيني'],
            'PL' => ['nationality' => 'Polish', 'nationality_ar' => 'بولندي'],
            'PT' => ['nationality' => 'Portuguese', 'nationality_ar' => 'برتغالي'],
            'QA' => ['nationality' => 'Qatari', 'nationality_ar' => 'قطري'],
            'RO' => ['nationality' => 'Romanian', 'nationality_ar' => 'روماني'],
            'RU' => ['nationality' => 'Russian', 'nationality_ar' => 'روسي'],
            'RW' => ['nationality' => 'Rwandan', 'nationality_ar' => 'رواندي'],
            'KN' => ['nationality' => 'Kittitian', 'nationality_ar' => 'كيتسي'],
            'LC' => ['nationality' => 'Saint Lucian', 'nationality_ar' => 'سانت لوسيا'],
            'VC' => ['nationality' => 'Vincentian', 'nationality_ar' => 'فنسنتي'],
            'WS' => ['nationality' => 'Samoan', 'nationality_ar' => 'ساموي'],
            'SM' => ['nationality' => 'Sammarinese', 'nationality_ar' => 'سان ماريني'],
            'ST' => ['nationality' => 'Sao Tomean', 'nationality_ar' => 'ساو تومي'],
            'SA' => ['nationality' => 'Saudi', 'nationality_ar' => 'سعودي'],
            'SN' => ['nationality' => 'Senegalese', 'nationality_ar' => 'سنغالي'],
            'RS' => ['nationality' => 'Serbian', 'nationality_ar' => 'صربي'],
            'SC' => ['nationality' => 'Seychellois', 'nationality_ar' => 'سيشلي'],
            'SL' => ['nationality' => 'Sierra Leonean', 'nationality_ar' => 'سيراليوني'],
            'SG' => ['nationality' => 'Singaporean', 'nationality_ar' => 'سنغافوري'],
            'SK' => ['nationality' => 'Slovak', 'nationality_ar' => 'سلوفاكي'],
            'SI' => ['nationality' => 'Slovenian', 'nationality_ar' => 'سلوفيني'],
            'SB' => ['nationality' => 'Solomon Islander', 'nationality_ar' => 'جزر سليمان'],
            'SO' => ['nationality' => 'Somali', 'nationality_ar' => 'صومالي'],
            'ZA' => ['nationality' => 'South African', 'nationality_ar' => 'جنوب أفريقي'],
            'SS' => ['nationality' => 'South Sudanese', 'nationality_ar' => 'جنوب سوداني'],
            'ES' => ['nationality' => 'Spanish', 'nationality_ar' => 'إسباني'],
            'LK' => ['nationality' => 'Sri Lankan', 'nationality_ar' => 'سريلانكي'],
            'SD' => ['nationality' => 'Sudanese', 'nationality_ar' => 'سوداني'],
            'SR' => ['nationality' => 'Surinamese', 'nationality_ar' => 'سورينامي'],
            'SZ' => ['nationality' => 'Swazi', 'nationality_ar' => 'سوازيلندي'],
            'SE' => ['nationality' => 'Swedish', 'nationality_ar' => 'سويدي'],
            'CH' => ['nationality' => 'Swiss', 'nationality_ar' => 'سويسري'],
            'SY' => ['nationality' => 'Syrian', 'nationality_ar' => 'سوري'],
            'TW' => ['nationality' => 'Taiwanese', 'nationality_ar' => 'تايواني'],
            'TJ' => ['nationality' => 'Tajik', 'nationality_ar' => 'طاجيكي'],
            'TZ' => ['nationality' => 'Tanzanian', 'nationality_ar' => 'تنزاني'],
            'TH' => ['nationality' => 'Thai', 'nationality_ar' => 'تايلندي'],
            'TL' => ['nationality' => 'Timorese', 'nationality_ar' => 'تيموري'],
            'TG' => ['nationality' => 'Togolese', 'nationality_ar' => 'توغولي'],
            'TO' => ['nationality' => 'Tongan', 'nationality_ar' => 'تونغي'],
            'TT' => ['nationality' => 'Trinidadian', 'nationality_ar' => 'ترينيدادي'],
            'TN' => ['nationality' => 'Tunisian', 'nationality_ar' => 'تونسي'],
            'TR' => ['nationality' => 'Turkish', 'nationality_ar' => 'تركي'],
            'TM' => ['nationality' => 'Turkmen', 'nationality_ar' => 'تركماني'],
            'TV' => ['nationality' => 'Tuvaluan', 'nationality_ar' => 'توفالي'],
            'UG' => ['nationality' => 'Ugandan', 'nationality_ar' => 'أوغندي'],
            'UA' => ['nationality' => 'Ukrainian', 'nationality_ar' => 'أوكراني'],
            'AE' => ['nationality' => 'Emirati', 'nationality_ar' => 'إماراتي'],
            'GB' => ['nationality' => 'British', 'nationality_ar' => 'بريطاني'],
            'US' => ['nationality' => 'American', 'nationality_ar' => 'أمريكي'],
            'UY' => ['nationality' => 'Uruguayan', 'nationality_ar' => 'أوروغواي'],
            'UZ' => ['nationality' => 'Uzbek', 'nationality_ar' => 'أوزبكي'],
            'VU' => ['nationality' => 'Ni-Vanuatu', 'nationality_ar' => 'فانواتي'],
            'VA' => ['nationality' => 'Vatican', 'nationality_ar' => 'فاتيكاني'],
            'VE' => ['nationality' => 'Venezuelan', 'nationality_ar' => 'فنزويلي'],
            'VN' => ['nationality' => 'Vietnamese', 'nationality_ar' => 'فيتنامي'],
            'YE' => ['nationality' => 'Yemeni', 'nationality_ar' => 'يمني'],
            'ZM' => ['nationality' => 'Zambian', 'nationality_ar' => 'زامبي'],
            'ZW' => ['nationality' => 'Zimbabwean', 'nationality_ar' => 'زيمبابوي'],
        ];

        foreach ($nationalities as $code => $data) {
            Country::where('code', $code)->update($data);
        }

        $this->command->info('Nationalities updated successfully!');
    }
}
